<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Test;

class TestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tests = [
            [
                'pertanyaan' => 'Saya merasa cemas tanpa alasan yang jelas',
                'opsi_a' => 'Tidak Pernah',
                'opsi_b' => 'Jarang',
                'opsi_c' => 'Kadang',
                'opsi_d' => 'Sering',
                'opsi_e' => 'Sangat Sering',
                'skor_a' => 0,
                'skor_b' => 1,
                'skor_c' => 2,
                'skor_d' => 3,
                'skor_e' => 4,
            ],
            [
                'pertanyaan' => 'Saya sulit tidur atau sering terbangun di malam hari',
                'opsi_a' => 'Tidak Pernah',
                'opsi_b' => 'Jarang',
                'opsi_c' => 'Kadang',
                'opsi_d' => 'Sering',
                'opsi_e' => 'Sangat Sering',
                'skor_a' => 0,
                'skor_b' => 1,
                'skor_c' => 2,
                'skor_d' => 3,
                'skor_e' => 4,
            ],
            [
                'pertanyaan' => 'Saya merasa lelah meskipun tidak melakukan aktivitas berat',
                'opsi_a' => 'Tidak Pernah',
                'opsi_b' => 'Jarang',
                'opsi_c' => 'Kadang',
                'opsi_d' => 'Sering',
                'opsi_e' => 'Sangat Sering',
                'skor_a' => 0,
                'skor_b' => 1,
                'skor_c' => 2,
                'skor_d' => 3,
                'skor_e' => 4,
            ],
            [
                'pertanyaan' => 'Saya kehilangan minat pada hal yang biasanya saya sukai',
                'opsi_a' => 'Tidak Pernah',
                'opsi_b' => 'Jarang',
                'opsi_c' => 'Kadang',
                'opsi_d' => 'Sering',
                'opsi_e' => 'Sangat Sering',
                'skor_a' => 0,
                'skor_b' => 1,
                'skor_c' => 2,
                'skor_d' => 3,
                'skor_e' => 4,
            ],
            [
                'pertanyaan' => 'Saya merasa sedih atau murung hampir setiap hari',
                'opsi_a' => 'Tidak Pernah',
                'opsi_b' => 'Jarang',
                'opsi_c' => 'Kadang',
                'opsi_d' => 'Sering',
                'opsi_e' => 'Sangat Sering',
                'skor_a' => 0,
                'skor_b' => 1,
                'skor_c' => 2,
                'skor_d' => 3,
                'skor_e' => 4,
            ],
            [
                'pertanyaan' => 'Saya sulit berkonsentrasi',
                'opsi_a' => 'Tidak Pernah',
                'opsi_b' => 'Jarang',
                'opsi_c' => 'Kadang',
                'opsi_d' => 'Sering',
                'opsi_e' => 'Sangat Sering',
                'skor_a' => 0,
                'skor_b' => 1,
                'skor_c' => 2,
                'skor_d' => 3,
                'skor_e' => 4,
            ],
            [
                'pertanyaan' => 'Saya merasa gelisah atau tidak tenang',
                'opsi_a' => 'Tidak Pernah',
                'opsi_b' => 'Jarang',
                'opsi_c' => 'Kadang',
                'opsi_d' => 'Sering',
                'opsi_e' => 'Sangat Sering',
                'skor_a' => 0,
                'skor_b' => 1,
                'skor_c' => 2,
                'skor_d' => 3,
                'skor_e' => 4,
            ],
            [
                'pertanyaan' => 'Saya mudah marah',
                'opsi_a' => 'Tidak Pernah',
                'opsi_b' => 'Jarang',
                'opsi_c' => 'Kadang',
                'opsi_d' => 'Sering',
                'opsi_e' => 'Sangat Sering',
                'skor_a' => 0,
                'skor_b' => 1,
                'skor_c' => 2,
                'skor_d' => 3,
                'skor_e' => 4,
            ],
            [
                'pertanyaan' => 'Saya merasa tidak percaya diri',
                'opsi_a' => 'Tidak Pernah',
                'opsi_b' => 'Jarang',
                'opsi_c' => 'Kadang',
                'opsi_d' => 'Sering',
                'opsi_e' => 'Sangat Sering',
                'skor_a' => 0,
                'skor_b' => 1,
                'skor_c' => 2,
                'skor_d' => 3,
                'skor_e' => 4,
            ],
            [
                'pertanyaan' => 'Saya merasa hidup saya tidak berarti',
                'opsi_a' => 'Tidak Pernah',
                'opsi_b' => 'Jarang',
                'opsi_c' => 'Kadang',
                'opsi_d' => 'Sering',
                'opsi_e' => 'Sangat Sering',
                'skor_a' => 0,
                'skor_b' => 1,
                'skor_c' => 2,
                'skor_d' => 3,
                'skor_e' => 4,
            ],
            [
                'pertanyaan' => 'Saya menarik diri dari lingkungan sosial',
                'opsi_a' => 'Tidak Pernah',
                'opsi_b' => 'Jarang',
                'opsi_c' => 'Kadang',
                'opsi_d' => 'Sering',
                'opsi_e' => 'Sangat Sering',
                'skor_a' => 0,
                'skor_b' => 1,
                'skor_c' => 2,
                'skor_d' => 3,
                'skor_e' => 4,
            ],
            [
                'pertanyaan' => 'Saya khawatir berlebihan tentang masa depan',
                'opsi_a' => 'Tidak Pernah',
                'opsi_b' => 'Jarang',
                'opsi_c' => 'Kadang',
                'opsi_d' => 'Sering',
                'opsi_e' => 'Sangat Sering',
                'skor_a' => 0,
                'skor_b' => 1,
                'skor_c' => 2,
                'skor_d' => 3,
                'skor_e' => 4,
            ],
            [
                'pertanyaan' => 'Saya sulit mengambil keputusan',
                'opsi_a' => 'Tidak Pernah',
                'opsi_b' => 'Jarang',
                'opsi_c' => 'Kadang',
                'opsi_d' => 'Sering',
                'opsi_e' => 'Sangat Sering',
                'skor_a' => 0,
                'skor_b' => 1,
                'skor_c' => 2,
                'skor_d' => 3,
                'skor_e' => 4,
            ],
            [
                'pertanyaan' => 'Saya merasa tertekan oleh tanggung jawab',
                'opsi_a' => 'Tidak Pernah',
                'opsi_b' => 'Jarang',
                'opsi_c' => 'Kadang',
                'opsi_d' => 'Sering',
                'opsi_e' => 'Sangat Sering',
                'skor_a' => 0,
                'skor_b' => 1,
                'skor_c' => 2,
                'skor_d' => 3,
                'skor_e' => 4,
            ],
            [
                'pertanyaan' => 'Saya merasa tidak memiliki harapan',
                'opsi_a' => 'Tidak Pernah',
                'opsi_b' => 'Jarang',
                'opsi_c' => 'Kadang',
                'opsi_d' => 'Sering',
                'opsi_e' => 'Sangat Sering',
                'skor_a' => 0,
                'skor_b' => 1,
                'skor_c' => 2,
                'skor_d' => 3,
                'skor_e' => 4,
            ],
        ];

        foreach ($tests as $test) {
            Test::create($test);
        }
    }
}
